image: golang:1.13

stages:
  - test
  - build
  - docker
  
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

test:
  stage: test
  before_script:
    - mkdir $GOPATH/src/exporter/
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
    - cd $GOPATH/src/exporter/
  script:
    - go test

build:
  stage: build
  dependencies:
    - test
  before_script:
    - mkdir $GOPATH/src/exporter/
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
    - cd $GOPATH/src/exporter/
  script:
    - go build *.go
    
docker:
  stage: docker
  image: docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/stephane5/cloudflare-prometheus-exporter:latest .
    - docker push registry.gitlab.com/stephane5/cloudflare-prometheus-exporter:latest