image: golang:1.13

stages:
  - test
  - build
  - docker
  
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

test:
  stage: test
  before_script:
    - mkdir $GOPATH/src/exporter/
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
    - cd $GOPATH/src/exporter/
  script:
    - go test

build:
  stage: build
  dependencies:
    - test
  before_script:
    - mkdir $GOPATH/src/exporter/
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
    - cd $GOPATH/src/exporter/
  script:
    - go build *.go
    
docker:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/stephane5/cloudflare-prometheus-exporter:latest .
    - docker push $CI_REGISTRY/stephane5/cloudflare-prometheus-exporter:latest