image: golang:1.13

stages:
  - test
  - build

before_script:
  - mkdir $GOPATH/src/exporter/
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
  - cd $GOPATH/src/exporter/

unit_tests:
  stage: test
  script:
    - go test

build:
  stage: build
  script:
    - go build *.go
    - docker build -t registry.gitlab.com/stephane5/cloudflare-prometheus-exporter:latest .
    - docker push registry.gitlab.com/stephane5/cloudflare-prometheus-exporter:latest
