image: golang:1.9

stages:
  - test
  - build

before_script:
  - mkdir $GOPATH/src/exporter/
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
  - cd $GOPATH/src/exporter/
  - go get -u github.com/golang/dep/cmd/dep
  - dep init
  - rm -rf vendor/github.com/cpuguy83/go-md2man/md2man/

unit_tests:
  stage: test
  script:
    - go test

build:
  stage: build
  script:
    - go build *.go