image: golang:1.13

stages:
  - test
  - build

before_script:
  - mkdir $GOPATH/src/exporter/
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/exporter/
  - cd $GOPATH/src/exporter/
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/urfave/cli
  - go get github.com/machinebox/graphql
  - ls
  - go version
  #- go get -u github.com/golang/dep/cmd/dep
  #- dep init

unit_tests:
  stage: test
  script:
    - go test

build:
  stage: build
  script:
    - go build *.go