{
 "title": "Cloudflare metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "zoneName", "query": "label_values(zoneName)" }
  ]
 },
 "panels": [
  {
   "title": "Cloudflare Metrics success rate",
   "type": "gauge",
   "description": "% of successful fetches against Cloudflare's metrics endpoint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(cloudflare_done_fetches + cloudflare_failed_fetches) / cloudflare_done_fetches * 100"
    }
   ]
  },
  {
   "title": "Request Bytes per cacheStatus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudflare_processed_bytes{zoneName=~\"$zoneName\"})by(cacheStatus)",
     "legendFormat": "{{cacheStatus}}"
    }
   ]
  },
  {
   "title": "Request # per HTTP Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudflare_requests_per_response_code{zoneName=~\"$zoneName\"})by(responseCode)",
     "legendFormat": "{{responseCode}}"
    }
   ]
  }
 ]
}